[2024-07-07T05:13:36.863+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T21:48:27.402576+00:00/task_id=AutoML_PyCaret permission to 509
[2024-07-07T05:13:36.868+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T21:48:27.402576+00:00 permission to 509
[2024-07-07T05:13:36.869+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo permission to 509
[2024-07-07T05:13:36.870+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-07-07T05:13:36.915+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T21:48:27.402576+00:00/task_id=AutoML_PyCaret permission to 509
[2024-07-07T05:13:36.919+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T21:48:27.402576+00:00 permission to 509
[2024-07-07T05:13:36.920+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo permission to 509
[2024-07-07T05:13:36.921+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-07-07T05:13:36.986+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AutoML_workflow_demo.AutoML_PyCaret manual__2024-07-06T21:48:27.402576+00:00 [queued]>
[2024-07-07T05:13:37.011+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AutoML_workflow_demo.AutoML_PyCaret manual__2024-07-06T21:48:27.402576+00:00 [queued]>
[2024-07-07T05:13:37.016+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-07-07T05:13:37.053+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): AutoML_PyCaret> on 2024-07-06 21:48:27.402576+00:00
[2024-07-07T05:13:37.063+0000] {standard_task_runner.py:60} INFO - Started process 1949 to run task
[2024-07-07T05:13:37.074+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'AutoML_workflow_demo', 'AutoML_PyCaret', 'manual__2024-07-06T21:48:27.402576+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dmc_pipeline.py', '--cfg-path', '/tmp/tmputtwm0hz']
[2024-07-07T05:13:37.087+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask AutoML_PyCaret
[2024-07-07T05:13:37.180+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T21:48:27.402576+00:00/task_id=AutoML_PyCaret permission to 509
[2024-07-07T05:13:37.182+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T21:48:27.402576+00:00 permission to 509
[2024-07-07T05:13:37.184+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo permission to 509
[2024-07-07T05:13:37.186+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-07-07T05:13:37.188+0000] {task_command.py:423} INFO - Running <TaskInstance: AutoML_workflow_demo.AutoML_PyCaret manual__2024-07-06T21:48:27.402576+00:00 [running]> on host 549d24f0d639
[2024-07-07T05:13:37.283+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AutoML_workflow_demo' AIRFLOW_CTX_TASK_ID='AutoML_PyCaret' AIRFLOW_CTX_EXECUTION_DATE='2024-07-06T21:48:27.402576+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-06T21:48:27.402576+00:00'
[2024-07-07T05:13:42.094+0000] {logging_mixin.py:188} INFO -                     Description                                 Value
0                    Session id                                   123
1                        Target                                Target
2                   Target type                            Multiclass
3                Target mapping  Dropout: 0, Enrolled: 1, Graduate: 2
4           Original data shape                           (76518, 37)
5        Transformed data shape                           (76518, 37)
6   Transformed train set shape                           (53562, 37)
7    Transformed test set shape                           (22956, 37)
8              Numeric features                                    36
9                    Preprocess                                  True
10              Imputation type                                simple
11           Numeric imputation                                  mean
12       Categorical imputation                                  mode
13               Fold Generator                       StratifiedKFold
14                  Fold Number                                    10
15                     CPU Jobs                                    -1
16                      Use GPU                                 False
17               Log Experiment                                 False
18              Experiment Name                      clf-default-name
19                          USI                                  7999
[2024-07-07T05:13:42.877+0000] {logging_mixin.py:188} WARNING - Processing:   0%|          | 0/61 [00:00<?, ?it/s]
[2024-07-07T05:13:43.074+0000] {logging_mixin.py:188} WARNING - Processing:   5%|4         | 3/61 [00:00<00:03, 15.30it/s]
[2024-07-07T05:14:02.885+0000] {logging_mixin.py:188} WARNING - Processing:   7%|6         | 4/61 [00:20<00:03, 15.30it/s]
[2024-07-07T05:19:32.109+0000] {logging_mixin.py:188} WARNING - Processing:   8%|8         | 5/61 [05:49<1:19:29, 85.16s/it]
[2024-07-07T05:19:32.779+0000] {logging_mixin.py:188} WARNING - Processing:  11%|#1        | 7/61 [05:49<45:17, 50.33s/it]  
[2024-07-07T05:20:03.299+0000] {logging_mixin.py:188} WARNING - Processing:  15%|#4        | 9/61 [06:20<32:22, 37.36s/it]
[2024-07-07T05:20:03.629+0000] {logging_mixin.py:188} WARNING - Processing:  18%|#8        | 11/61 [06:20<20:25, 24.50s/it]
[2024-07-07T05:20:06.315+0000] {logging_mixin.py:188} WARNING - Processing:  21%|##1       | 13/61 [06:23<13:28, 16.85s/it]
[2024-07-07T05:20:06.596+0000] {logging_mixin.py:188} WARNING - Processing:  25%|##4       | 15/61 [06:23<08:48, 11.49s/it]
[2024-07-07T05:20:15.121+0000] {logging_mixin.py:188} WARNING - Processing:  28%|##7       | 17/61 [06:32<06:45,  9.22s/it]
[2024-07-07T05:20:15.372+0000] {logging_mixin.py:188} WARNING - Processing:  31%|###1      | 19/61 [06:32<04:28,  6.40s/it]
[2024-07-07T05:21:15.099+0000] {logging_mixin.py:188} WARNING - Processing:  34%|###4      | 21/61 [07:32<09:03, 13.60s/it]
[2024-07-07T05:21:15.458+0000] {logging_mixin.py:188} WARNING - Processing:  38%|###7      | 23/61 [07:32<06:01,  9.51s/it]
[2024-07-07T05:21:18.593+0000] {logging_mixin.py:188} WARNING - Processing:  41%|####      | 25/61 [07:35<04:15,  7.10s/it]
[2024-07-07T05:21:19.207+0000] {logging_mixin.py:188} WARNING - Processing:  44%|####4     | 27/61 [07:36<02:51,  5.05s/it]
[2024-07-07T05:21:45.206+0000] {logging_mixin.py:188} WARNING - Processing:  48%|####7     | 29/61 [08:02<03:58,  7.45s/it]
[2024-07-07T05:21:45.529+0000] {logging_mixin.py:188} WARNING - Processing:  51%|#####     | 31/61 [08:02<02:37,  5.25s/it]
[2024-07-07T05:21:49.337+0000] {logging_mixin.py:188} WARNING - Processing:  54%|#####4    | 33/61 [08:06<01:58,  4.25s/it]
[2024-07-07T05:21:49.594+0000] {logging_mixin.py:188} WARNING - Processing:  57%|#####7    | 35/61 [08:06<01:18,  3.01s/it]
[2024-07-07T05:22:11.994+0000] {logging_mixin.py:188} WARNING - Processing:  61%|######    | 37/61 [08:29<02:11,  5.47s/it]
[2024-07-07T05:22:12.322+0000] {logging_mixin.py:188} WARNING - Processing:  64%|######3   | 39/61 [08:29<01:25,  3.88s/it]
[2024-07-07T05:26:18.986+0000] {logging_mixin.py:188} WARNING - Processing:  67%|######7   | 41/61 [12:36<13:14, 39.74s/it]
[2024-07-07T05:26:19.458+0000] {logging_mixin.py:188} WARNING - Processing:  70%|#######   | 43/61 [12:36<08:21, 27.88s/it]
[2024-07-07T05:26:30.443+0000] {logging_mixin.py:188} WARNING - Processing:  74%|#######3  | 45/61 [12:47<05:38, 21.16s/it]
[2024-07-07T05:26:31.591+0000] {logging_mixin.py:188} WARNING - Processing:  77%|#######7  | 47/61 [12:48<03:29, 14.98s/it]
[2024-07-07T05:27:06.514+0000] {logging_mixin.py:188} WARNING - Processing:  80%|########  | 49/61 [13:23<03:08, 15.73s/it]
[2024-07-07T05:27:06.856+0000] {logging_mixin.py:188} WARNING - Processing:  84%|########3 | 51/61 [13:23<01:50, 11.06s/it]
[2024-07-07T05:32:29.815+0000] {job.py:213} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 308, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-07-07T05:32:29.956+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-07-07T05:40:35.154+0000] {local_task_job_runner.py:234} INFO - Task exited with return code -9
[2024-07-07T05:40:35.620+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
