[2024-07-06T22:51:20.915+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T21:48:27.402576+00:00/task_id=SubmitKaggle permission to 509
[2024-07-06T22:51:20.917+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T21:48:27.402576+00:00 permission to 509
[2024-07-06T22:51:20.918+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo permission to 509
[2024-07-06T22:51:20.919+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-07-06T22:51:20.941+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T21:48:27.402576+00:00/task_id=SubmitKaggle permission to 509
[2024-07-06T22:51:20.941+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T21:48:27.402576+00:00 permission to 509
[2024-07-06T22:51:20.942+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo permission to 509
[2024-07-06T22:51:20.943+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-07-06T22:51:20.961+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AutoML_workflow_demo.SubmitKaggle manual__2024-07-06T21:48:27.402576+00:00 [queued]>
[2024-07-06T22:51:20.966+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AutoML_workflow_demo.SubmitKaggle manual__2024-07-06T21:48:27.402576+00:00 [queued]>
[2024-07-06T22:51:20.966+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-06T22:51:20.976+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): SubmitKaggle> on 2024-07-06 21:48:27.402576+00:00
[2024-07-06T22:51:20.983+0000] {standard_task_runner.py:60} INFO - Started process 3699 to run task
[2024-07-06T22:51:20.985+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'AutoML_workflow_demo', 'SubmitKaggle', 'manual__2024-07-06T21:48:27.402576+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dmc_pipeline.py', '--cfg-path', '/tmp/tmpc2ve84ha']
[2024-07-06T22:51:20.986+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask SubmitKaggle
[2024-07-06T22:51:21.013+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T21:48:27.402576+00:00/task_id=SubmitKaggle permission to 509
[2024-07-06T22:51:21.014+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T21:48:27.402576+00:00 permission to 509
[2024-07-06T22:51:21.015+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo permission to 509
[2024-07-06T22:51:21.016+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-07-06T22:51:21.017+0000] {task_command.py:423} INFO - Running <TaskInstance: AutoML_workflow_demo.SubmitKaggle manual__2024-07-06T21:48:27.402576+00:00 [running]> on host 549d24f0d639
[2024-07-06T22:51:21.063+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AutoML_workflow_demo' AIRFLOW_CTX_TASK_ID='SubmitKaggle' AIRFLOW_CTX_EXECUTION_DATE='2024-07-06T21:48:27.402576+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-06T21:48:27.402576+00:00'
[2024-07-06T22:51:21.067+0000] {logging_mixin.py:188} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2024-07-06T22:51:21.181+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dmc_pipeline.py", line 104, in SubmitKaggle
    predictions = predict_model(final_model, data=df_test)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pycaret/classification/functional.py", line 2172, in predict_model
    return experiment.predict_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pycaret/classification/oop.py", line 2824, in predict_model
    return super().predict_model(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py", line 4936, in predict_model
    raise ValueError(
ValueError: If estimator is not a Pipeline, you must run setup() first.
[2024-07-06T22:51:21.191+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=AutoML_workflow_demo, task_id=SubmitKaggle, execution_date=20240706T214827, start_date=20240706T225120, end_date=20240706T225121
[2024-07-06T22:51:21.199+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 20 for task SubmitKaggle (If estimator is not a Pipeline, you must run setup() first.; 3699)
[2024-07-06T22:51:21.238+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-06T22:51:21.250+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
